name: Publish API Test Report


on:
  workflow_run:
    workflows: ["API Automation Tests"]
    types:
      - completed


permissions:
  contents: read
  pages: write
  id-token: write


jobs:

  deploy-report:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Setup Pages
      uses: actions/configure-pages@v5


    - name: Download Test Report Artifact
      uses: actions/download-artifact@v4

      with:
        name: Newman-API-Test-Report
        path: report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}


    - name: Prepare Static Site

      run: |

        echo "Listing downloaded files..."
        ls -R report
        
        mkdir public

    - name: Upload Pages Artifact

      uses: actions/upload-pages-artifact@v3

      with:

        path: public



    - name: Deploy To GitHub Pages

      uses: actions/deploy-pages@v4
